import { Entry } from './entry';

export const ENTRIES: Entry[]= [

  {
    title: 'Meandering #1: Email Marketing System, Part 1',
    date: '05/04/2017',
    objective: 'Using SaaS (software as a service) is expensive, and requires additional awkward tinkering when using multiple instances of SaaS. Let\'s build our own, and let\'s do it better!',
    content: 'E-books and the like are a popular way for content generators to make money with their knowledge via the world wide web. In an age where people are seeking immediate answers to their questions, ebooks allow content generators to sell their expertise electronically, and with little hassle- especially when compared with venturing to Barnes and Noble. While there is no shortage of clientele for these products, often finding said clientele is the real challenge. Content generators need to find their target market before they can start turning capital, and many choose to do so through lead generation and email marketing. There is plenty of software on the market that perform both of these functions- a Google search will reveal a plethora of businesses specializing in exactly this sort of marketing strategy. A quick look through each of these Googled results will also reveal the cost of such services, which will vary widely, but given that these services are paid in monthly installments, the costs can add up quickly. When one also factors in the cost of server space and other business cost, the extra monthly expenditures can become significant.So, what if, as a developer, I wanted to market my own ebooks or tutorials, but I don’t want to pay for someone else’s code to do so? It\’s simple(?), I\’ll make my own!  How does one go about that? My objective for the first few entries of this blog is to find out. Ultimately, I want to build an application that will do the following WITHOUT using any paid SaaS, or using any other software where I am not in full control of my code. <br><br><p> By then end of this project, I want a deployed application that will: <ol><li>Collect leads from prospective clients</li><li>Record information about the user, to include their name and email address</li><li>Send out an email to enrolled clients based on information collected by them</li></ol></p><p>And since the idea of this blog is to utilize the tools and technologies of the MEAN stack (Mongo DB, ECMA Script, Angular, and NodeJS) the project will ideally be completed using only those languages and frameworks. The only deviations will make on this is for front-end styling frameworks (specifically, Twitter Bootstrap). I plan to approach this project from an AGILE standpoint (that is to say, there will be wireframes, user stories, etc.), and, while at the time of this writing, there are no collaboraters, it is possible in the future that there could be. Also, as a quick disclaimer: this project is meant to focus on the development portion of email marketting, and not as much on the marketting theory behind it; as I generate the content in the application, please bear in mind that I have limited knoweldge of best practices in marketing, and such content is meant only to be a very basic example.<p>Stay tuned for Part 2, where I will be going over wireframes and user stories.</p><h3>-Tom</h3>',
  }
];
